### ISSUE TITLE
Any progress? 

### ISSUE THREAD

**Issue by Ziepoeskenetnie** [GaryOkie/pynx584#1]

**Comment by GaryOkie** [comment]
Nah - sorry.   I quit further attempts to resolve run-time errors since I had a perfectly usable Vera hub dedicated to the serial connection that is also providing all the CADDX binary switches/sensors to HASS.     As a backup, I also have pynx584 working on a Pi for the serial connection.

**Comment by Ziepoeskenetnie** [comment]
Great, does it work on a Raspberry pi zero 2 w?

**Comment by GaryOkie** [comment]
I have not personally tried it, but I think the Pynx584 code should run fine on any Pi zero.    

For pynx584 support - refer to https://github.com/kk7ds/pynx584

Good news - one of the [issues ](https://github.com/kk7ds/pynx584/issues/72)was a request to host a pynx584 HASS addon that someone else got working.   So you can use this guys code as an option:  https://github.com/ivmarkov/nx584
